---
Name: schema
After:
  - 'framework'
  - 'cms'
---
DevelopmentAdmin:
  registered_controllers:
      build:
        controller: 'SchemaBuildExtension'
Member:
  extensions:
    - SchemaObjectExtension
SiteConfig:
  extensions:
    - SchemaObjectExtension
SiteTree:
  extensions:
    - SchemaObjectExtension
File:
  extensions:
    - SchemaObjectExtension
Schema:
  core_default_enabled_schemas:
    - Organization
    - WebSite
    - WebPage
SchemaProperty:
  core_dynamic_value_options:
    Member:
      '->getName()'       : 'Members Full Name'
      '->FirstName'       : 'Members First Name'
      '->Surname'         : 'Members Surname'
      '->Email'           : 'Members E-mail'
      '->Locale'          : 'Members Language'
    SiteConfig:
      '->Title'           : 'Site Name'
      '->Tagline'         : 'Site Tag Line'
    SiteTree:
      '->Link()'          : 'URL'
      '->getMenuTitle()'  : 'Title'
      '->Breadcrumbs()'   : 'Breadcrumbs'
      '->Created'         : 'Created At'
      '->LastEdited'      : 'Edited On'
    File:
      '->Link()'          : 'URL'
      '->Title'           : 'Title'
      '->appCategory()'   : 'Category'
      '->getExtension()'  : 'Extension'
      '->getFileType()'   : 'File Type'
      '->getSize()'       : 'Size'
    i18n:
      '::get_locale()'    : 'Default Locale'
